services:
#---------------------------------------------------
#Plex Video and Media
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./plex/config/:/config
      - /mnt/docker/series:/series
      - /mnt/docker/peliculas/:/peliculas
    restart: unless-stopped